import { connectDB } from "@/lib/db";
import Faq from "@/models/Faq";

export interface FaqData { _id: string; question: string; answer: string; category: string; categoryDescription: string; linkLabel: string; linkHref: string; displayOrder: number; status: "published" | "hidden" }

export const STARTER_FAQS: FaqData[] = [
  { _id: "faq-01", question: "What exactly do I receive?", answer: "The complete source code, database schema with sample data, installation guide and technical documentation. Everything listed under ‘What you receive’ on the product page is delivered through your account.", category: "Buying & billing", categoryDescription: "Products, demos, payments and refunds", linkLabel: "", linkHref: "", displayOrder: 10, status: "published" },
  { _id: "faq-02", question: "Can I try it before buying?", answer: "Yes. Product pages can include live web, app and admin demos so you can check the customer experience and management workflow before choosing a package.", category: "Buying & billing", categoryDescription: "Products, demos, payments and refunds", linkLabel: "", linkHref: "", displayOrder: 20, status: "published" },
  { _id: "faq-03", question: "Do I have to pay anything monthly?", answer: "No Techbront platform fee is charged. Your own hosting, domain and any third-party services required by the product are separate recurring costs.", category: "Buying & billing", categoryDescription: "Products, demos, payments and refunds", linkLabel: "", linkHref: "", displayOrder: 30, status: "published" },
  { _id: "faq-04", question: "Can I get a refund?", answer: "Before the source is delivered, eligible purchases can be refunded under the current refund policy. After delivery, refunds are limited because you hold a permanent copy of the product.", category: "Buying & billing", categoryDescription: "Products, demos, payments and refunds", linkLabel: "Read the refund policy", linkHref: "/refund-policy", displayOrder: 40, status: "published" },
  { _id: "faq-05", question: "Will I get a GST invoice?", answer: "Yes. An invoice is generated for every completed order. Add your GSTIN during checkout when applicable.", category: "Buying & billing", categoryDescription: "Products, demos, payments and refunds", linkLabel: "", linkHref: "", displayOrder: 50, status: "published" },
  { _id: "faq-06", question: "Can an agency use one licence for several clients?", answer: "One standard licence covers one end product. A second client project requires another licence unless a separate multi-project agreement has been confirmed.", category: "Licence & ownership", categoryDescription: "How you may use and customise the code", linkLabel: "Read the licence terms", linkHref: "/licence", displayOrder: 60, status: "published" },
  { _id: "faq-07", question: "Can I modify the code and remove Techbront branding?", answer: "Yes. You may customise the product and launch it under your own brand. You may not resell or republish the original source code as a competing source-code product.", category: "Licence & ownership", categoryDescription: "How you may use and customise the code", linkLabel: "", linkHref: "", displayOrder: 70, status: "published" },
  { _id: "faq-08", question: "What support is included?", answer: "Your package includes the setup support stated on its product page. Custom development, third-party changes and ongoing maintenance are scoped separately.", category: "Setup & support", categoryDescription: "Installation, assistance and custom requirements", linkLabel: "", linkHref: "", displayOrder: 80, status: "published" },
  { _id: "faq-09", question: "Can you install it for me?", answer: "Yes. When deployment is included, we configure the approved hosting environment, domain and SSL certificate, then complete the agreed handover.", category: "Setup & support", categoryDescription: "Installation, assistance and custom requirements", linkLabel: "Book a discussion", linkHref: "/book-consultation#book-appointment", displayOrder: 90, status: "published" },
  { _id: "faq-10", question: "What if I need something that is not in the catalogue?", answer: "Techbront can customise the closest product or scope a custom build. Share your workflow and required features so the team can recommend the best starting point.", category: "Setup & support", categoryDescription: "Installation, assistance and custom requirements", linkLabel: "Tell us what you need", linkHref: "/contact?type=custom", displayOrder: 100, status: "published" },
];

let seeded = false;
export async function ensureStarterFaqs() { if (seeded) return; await connectDB(); if ((await Faq.countDocuments({})) === 0) await Faq.insertMany(STARTER_FAQS.map(({ _id, ...faq }) => faq)); seeded = true; }
export async function getPublishedFaqs(): Promise<FaqData[]> { try { await ensureStarterFaqs(); return JSON.parse(JSON.stringify(await Faq.find({ status: "published" }).sort({ displayOrder: 1, createdAt: 1 }).lean())) as FaqData[]; } catch { return STARTER_FAQS; } }
